# Generated by Django 4.2.1 on 2023-05-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quesmodel',
            name='typeq',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
