# Generated by Django 4.2.1 on 2023-05-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enword', models.CharField(max_length=40, verbose_name='Английское слова')),
                ('ruword', models.CharField(max_length=40, verbose_name='Английское слова')),
            ],
        ),
    ]
